# Generated by Django 4.1.5 on 2024-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Дата')),
                ('exercise_type', models.CharField(max_length=200, verbose_name='Вид примеров')),
                ('total', models.IntegerField(verbose_name='Всего')),
                ('correct_answers', models.IntegerField(verbose_name='Правильных')),
                ('wrong_answers', models.IntegerField(verbose_name='Неправильных')),
            ],
        ),
    ]
