# Generated by Django 4.1.5 on 2024-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathstatistics',
            name='count10_correct',
            field=models.IntegerField(default=None, verbose_name='Сложение до 10 правильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='count10_incorrect',
            field=models.IntegerField(default=None, verbose_name='Сложение до 10 неправильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='equation10_correct',
            field=models.IntegerField(default=None, verbose_name='Уравнение до 10 правильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='equation10_incorrect',
            field=models.IntegerField(default=None, verbose_name='Уравнение до 10 неправильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='multiplication_correct',
            field=models.IntegerField(default=None, verbose_name='Умножение правильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='multiplication_incorrect',
            field=models.IntegerField(default=None, verbose_name='Умножение неправильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='subtr10_correct',
            field=models.IntegerField(default=None, verbose_name='Вычитание до 10 правильных'),
        ),
        migrations.AddField(
            model_name='mathstatistics',
            name='subtr10_incorrect',
            field=models.IntegerField(default=None, verbose_name='Вычитание до 10 неправильных'),
        ),
    ]
