# Generated by Django 4.1.5 on 2024-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0003_remove_mathstatistics_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathstatistics',
            name='count10_correct',
            field=models.IntegerField(null=True, verbose_name='Сложение до 10 правильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='count10_incorrect',
            field=models.IntegerField(null=True, verbose_name='Сложение до 10 неправильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='equation10_correct',
            field=models.IntegerField(null=True, verbose_name='Уравнение до 10 правильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='equation10_incorrect',
            field=models.IntegerField(null=True, verbose_name='Уравнение до 10 неправильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='multiplication_correct',
            field=models.IntegerField(null=True, verbose_name='Умножение правильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='multiplication_incorrect',
            field=models.IntegerField(null=True, verbose_name='Умножение неправильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='subtr10_correct',
            field=models.IntegerField(null=True, verbose_name='Вычитание до 10 правильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='subtr10_incorrect',
            field=models.IntegerField(null=True, verbose_name='Вычитание до 10 неправильных'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='timer',
            field=models.IntegerField(null=True, verbose_name='timer'),
        ),
        migrations.AlterField(
            model_name='mathstatistics',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Всего'),
        ),
    ]
