# Generated by Django 4.1.5 on 2024-03-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0004_alter_mathstatistics_count10_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
