# Generated by Django 4.1.5 on 2024-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0005_index_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_image',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
