# Generated by Django 4.1.5 on 2024-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0006_alter_index_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathstatistics',
            name='timer',
        ),
        migrations.AlterField(
            model_name='index_image',
            name='image',
            field=models.ImageField(upload_to='mathapp/static/images'),
        ),
    ]
